### ISSUE TITLE
[zabbix-agent2] "PersistentBufferFile" parameter is not empty but "EnablePersistentBuffer" is not set.

### ISSUE THREAD

**Issue by neothematrix** [zabbix/zabbix-docker#1600]
hello!
since last zabbix-agent2 image update, zabbix-agent is not starting anymore throwing this error:

`ERROR: Failed to run agent: cannot prepare result cache: "PersistentBufferFile" parameter is not empty but "EnablePersistentBuffer" is not set.`

upon debugging, it turns out that "ZBX_PERSISTENTBUFFERFILE" is set at dockerfile level, but "ZBX_ENABLEPERSISTENTBUFFER" is false by default.

It seems in previous version of the image, the docker-entrypoint.sh was unsetting the ZBX_PERSISTENTBUFFERFILE environment variable probably in the wrong part: https://github.com/zabbix/zabbix-docker/commit/5172cab191170b5af5d6ab23dfffef8de38b17da#diff-7dd0d975a2f29c788db0766e7fd04771b28bf5b581a9b4f8aaf10981890a99ddL183 and it was now corrected but the unset should be of "ZBX_PERSISTENTBUFFERFILE" not of "ZBX_ENABLEPERSISTENTBUFFER".

**Comment by dotneft** [comment]
What image do you use? The mistake you show already fixed in latest images.

**Comment by neothematrix** [comment]
hello @dotneft 
I'm using:

docker image ls --digests |grep zabbix-agent2
`zabbix/zabbix-agent2                         latest        sha256:51d679ecce112902e592fd8b5821611e10e64cf6cbae5a48e04e5da0b1daaa8c   830917787607   39 hours ago    73.3MB`

and the issue seems to be still present

**Comment by dotneft** [comment]
for me works fine:
```
 % docker run --name test -d -e ZBX_ENABLEPERSISTENTBUFFER=true zabbix/zabbix-agent2
29ad1a45e069a37203a7c4a648ac1404fad67443a1af1a3ba0e831c94b78172d
dotneft@MacBook-Pro-2 zabbix-docker % docker exec -ti test ls -lah /var/lib/zabbix/buffer/
total 40K
drwxrwsr-x 1 zabbix root  18 Jan  2 11:39 .
drwxrwsr-x 1 zabbix root  12 Dec 31 20:16 ..
-rw-r--r-- 1 zabbix root 36K Jan  2 11:39 agent2.db
```

**Comment by neothematrix** [comment]
right, but if you start the image without passing ZBX_ENABLEPERSISTENTBUFFER environment or setting it to "false" the container won't start with the message: 

ERROR: Failed to run agent: cannot prepare result cache: "PersistentBufferFile" parameter is not empty but "EnablePersistentBuffer" is not set.

I woud expect it to start but without using the bufferfile as it was happening earlier.

**Comment by dotneft** [comment]
Got it! Will be fixed soon.

**Comment by neothematrix** [comment]
tested with the just pushed zabbix-agent2:latest tag and it's now working as expected!
thanks!

**Comment by dotneft** [comment]
どういたしまして。
