### ISSUE TITLE
5.0 latest image not up-to-date

### ISSUE THREAD

**Issue by x-jokay** [zabbix/zabbix-docker#702]
It seems the `-5.0-latest` image are not up-to-date?

| Image | Last pushed |
|-|-|
| [zabbix/zabbix-server-pgsql:centos-5.0-latest](https://hub.docker.com/layers/zabbix/zabbix-server-pgsql/centos-5.0-latest/images/sha256-89fed2908c43b85063a0c4f5d9626a2bcafb69490be6995d5cc5f22ac70b337a?context=explore) | a month ago |
| [zabbix/zabbix-server-pgsql:centos-5.0.3](https://hub.docker.com/layers/zabbix/zabbix-server-pgsql/centos-5.0.3/images/sha256-c7e5feab199d9449f3bb188bb5503d35fe01762149e6aef9c9a6b4008a679e8c?context=explore) | 2 days ago |

**Comment by dotneft** [comment]
Yes, looks like :-) Thank you! Will be rebuilt soon.

**Comment by x-jokay** [comment]
Thank you :wink:

**Comment by dotneft** [comment]
Fixed!

**Comment by x-jokay** [comment]
@dotneft I'm sorry but as of now [zabbix/zabbix-server-pgsql:centos-5.0-latest](https://hub.docker.com/layers/zabbix/zabbix-server-pgsql/centos-5.0-latest/images/sha256-89fed2908c43b85063a0c4f5d9626a2bcafb69490be6995d5cc5f22ac70b337a?context=explore) seems still not up-to-date :confused:

![zabbix-5 0](https://user-images.githubusercontent.com/18613935/91476167-e3a4ec00-e89c-11ea-9762-8e147a097314.png)

**Comment by dotneft** [comment]
agree ( Not sure why it happens, I checked centos-latest.

**Comment by x-jokay** [comment]
Thx, this time it worked :+1:
